version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: organicnow-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8080
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: organicnow-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://organicnow-db:5432/apartmant_management
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - database

  database:
    image: postgres:17-alpine
    container_name: organicnow-db
    restart: always
    environment:
      - POSTGRES_DB=apartmant_management
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql  # 👈 mount script init

volumes:
  postgres_data:
