version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: organicnow-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:8080
    command: npm run dev -- --host 0.0.0.0 --port 5173
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: organicnow-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/apartment_management
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      database:
        condition: service_healthy   # รอจน DB พร้อมก่อน

  database:
    image: postgres:17-alpine
    container_name: organicnow-db
    restart: always
    environment:
      - POSTGRES_DB=apartment_management
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:                      # ✅ ตรวจสุขภาพ DB
      test: ["CMD-SHELL", "pg_isready -U postgres -d apartment_management || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  postgres_data:
