name: Build & Push Docker Images

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NS: ${{ secrets.DOCKERHUB_USERNAME }}   # ชื่อ namespace/username บน Docker Hub
      FULL_SHA: ${{ github.sha }}             # ยังไม่ตัด ให้ตัดใน shell

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: backend
            context: ./backend
            dockerfile: ./backend/Dockerfile
            image: organicnow-backend
          - name: frontend
            context: ./frontend
            dockerfile: ./frontend/Dockerfile
            image: organicnow-frontend

    steps:
      - name: Sanity check secrets (no values printed)
        run: |
          test -n "${{ secrets.DOCKERHUB_USERNAME }}" && echo "USERNAME: OK" || (echo "USERNAME: MISSING" && exit 1)
          test -n "${{ secrets.DOCKERHUB_TOKEN }}" && echo "TOKEN: OK" || (echo "TOKEN: MISSING" && exit 1)
    
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Compute tags
        id: meta
        run: |
          SHORT_SHA="${FULL_SHA::7}"
          IMAGE="${NS}/${{ matrix.image }}"
          TAGS="$IMAGE:latest,$IMAGE:${SHORT_SHA}"

          # ถ้ามี git tag เช่น v1.2.3 ให้เติม tag นั้นด้วย
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            TAGS="$TAGS,$IMAGE:${GITHUB_REF_NAME}"
          fi

          echo "image=${IMAGE}" >> "$GITHUB_OUTPUT"
          echo "tags=${TAGS}"   >> "$GITHUB_OUTPUT"

      - name: Build & Push ${{ matrix.name }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # platforms: linux/amd64,linux/arm64   # ถ้าต้อง multi-arch ค่อยปลด
